### ISSUE TITLE
While using Mystic Mist Staff, teleport spells that require water or air runes are not considered.

### ISSUE THREAD

**Issue by Hyatice** [Skretzo/shortest-path#127]
I'm sure this applies to other staves (possibly only combination staves or mystic staves?) but if I set a path to center of Varrock, for example, while wielding the mystic mist staff and carrying fire runes, earth runes and law runes, it will direct me to Civitas to take the quetzal. If I disable Quetzal, it will direct me to a fairy ring somewhere instead.

If I take out air and water runes, however, it correctly tells me to use the varrock tele.

**Comment by Hyatice** [comment]
Can confirm this also happens with a Smoke staff.

As an alternative solution, a simple "Always assume all elemental runes" checkbox in settings would do wonders. e.g. if you have law runes in your inventory, show *all* teleports for your current spellbook regardless.

**Comment by Skretzo** [comment]
Combination runes and staves are currently not working correctly or simply missing. I want to add this, but doing it properly is a bit difficult. For example, I believe this should be all the different combinations that you can use for the Varrock Teleport spell (the "duplicates" are mystic staff versions), and some of the other teleports are even worse. The difficult part is correctly generating them automatically, because I don't want to type them all out manually.

![Image](https://github.com/user-attachments/assets/008c5660-6e83-4ef2-a3a1-4495a1b2b719)

**Comment by Skretzo** [comment]
@emerald000 "Checking how many of each rune you have access to" is a good suggestion. However, I am not sure how I can "filter the teleports based on that" without knowing all possible item requirement permutations for all teleport spells. The problem is not really checking which runes are available, it is rather knowing which runes belong to which teleport(s).

**Comment by Skretzo** [comment]
@emerald000 Ah, you are right. That makes sense. How does `getRuneCount(Rune.AIR) >= 3` ensure that e.g. `1 Staff of air`, `1 Staff of fire` and `1 Law rune` does not let you cast Varrock Teleport (because it is impossible to equip both staves)?

**Comment by Hyatice** [comment]
> [@emerald000](https://github.com/emerald000) Ah, you are right. That makes sense. How does `getRuneCount(Rune.AIR) >= 3` ensure that e.g. `1 Staff of air`, `1 Staff of fire` and `1 Law rune` does not let you cast Varrock Teleport (because it is impossible to equip both staves at once)?

Hmmm... the only way I can think of is a bit messy, but definitely less messy than hard coding every possible item combo per tele. pseudo-code incoming...

Inventory: 100 Law, Fire Staff, Dust Staff

Dust Staff counts as mainAir, mainEarth and mainAirEarth

mainAir=True
mainEarth=True
mainFire=True
mainWater=False
mainAirEarth=True
mainAirFire=False
mainAirWater=False
mainEarthFire=False
mainEarthWater=False
mainFireWater=False
offhandEarth=False
offhandFire=False
offhandWater=False

Check if there are sufficient "True" runes to cast the spell, keeping track of what is needed, and use boolean logic to remove options so only 'possible' combinations fall out the end.

so in this case:
needAir=True
needEarth=False
needFire=True
needWater=False

if needAir:
   if not mainAir:
      return(False)
   if needEarth:
      if not mainAirEarth and not offhandEarth:
         return(False)
   if needFire:
      if not mainAirFire and not offhandFire:
         return(False)
   if needWater:
      if not mainAirWater and not offhandWater:
         return(False)

if needEarth and not mainEarth and not offhandEarth:
   return(False)
if needFire and not mainFire and not offhandFire:
   return(False)
if needWater and not mainWater and not offhandWater:
   return(False)

return(True)

**Comment by Hyatice** [comment]
Excellent! I'm not familiar with runelite coding (though it looks suspiciously like Python?) and most of my coding experience is in batch script of all things.. I look forward to when this is implemented!

**Comment by Skretzo** [comment]
Could you please check if this works correctly now in version 1.17?

**Comment by NotBlackice** [comment]
I can't test other staves, but I can confirm it does not work with "air battlestaff". Seems you forgot the elemental battlestaves.

**Comment by Skretzo** [comment]
> I can't test other staves, but I can confirm it does not work with "air battlestaff". Seems you forgot the elemental battlestaves.

Thank you for checking. Yes, I did forget air, earth, fire and water battlestaff. It should be fixed now. Feel free to check if it works correctly now with version 1.17.5.

**Comment by gamedevnet** [comment]
Hey, just wanted to mention that this is still a problem with Mist battlestaff!

**Comment by FIrgolitsch** [comment]
These issues should all be fixed now

**Comment by Turtl3Dragon** [comment]
This issue is still present with Dust Battlestaff. I try it without any runes (earth or air runes) and it tells me to tele to GE, I have either earth or air rune in my inventory then it properly tells me to tele to POH. 
It seems to act as one element staff either air or earth and not both at the same time. 

I'm not sure about the other staffs as i haven't tried them.

**Comment by FIrgolitsch** [comment]
Thanks for letting me know. I’ll have a look at that.

**Comment by Nannerz** [comment]
Still an issue with the Mystic Smoke Staff as well.

**Comment by MegaSpyDev** [comment]
I can confirm that the Mystic Air Staff isn't currently configured as a variation of the Staff of Air either.

**Comment by smithtrenton** [comment]
Double up on the Mystic Air Staff not working
